name: Count Lines of Code

on:
  schedule:
    - cron: "* */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install cloc
        run: |
          sudo apt-get install -y cloc

      - name: Count lines of code
        id: cloc
        run: |
          cloc --json . > cloc.json
          cat cloc.json  # Debugging output
          echo "::set-output name=total_lines::$(jq '.sum.code' cloc.json)"

      - name: Create/update README with total lines
        run: |
          TOTAL_LINES="${{ steps.cloc.outputs.total_lines }}"
          echo "## Total Lines of Code: $TOTAL_LINES" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update total lines of code" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
